const products = [
  {
    id: 1,
    name: "Aero Run",
    category: "Running",
    price: 2499,
    quantity: 10,
    description: "Lightweight shoes designed for everyday running.",
  },
  {
    id: 2,
    name: "Urban Classic",
    category: "Sneakers",
    price: 1999,
    quantity: 8,
    description: "Comfortable sneakers for casual everyday wear.",
  },
  {
    id: 3,
    name: "Luca Loafers",
    category: "Loafers",
    price: 2999,
    quantity: 3,
    description: "Classic loafers suitable for formal and casual outfits.",
  },
  {
    id: 4,
    name: "Street High",
    category: "Sneakers",
    price: 2799,
    quantity: 6,
    description: "Stylish high-top sneakers with a comfortable fit.",
  },
  {
    id: 5,
    name: "Coast Sandals",
    category: "Sandals",
    price: 999,
    quantity: 0,
    description: "Simple and comfortable sandals for everyday use.",
  },
  {
    id: 6,
    name: "Trail Pro",
    category: "Hiking",
    price: 3499,
    quantity: 12,
    description: "Durable shoes designed for outdoor hiking.",
  },
  {
    id: 7,
    name: "Easy Walk",
    category: "Slip-ons",
    price: 1499,
    quantity: 2,
    description: "Easy-to-wear slip-ons for everyday comfort.",
  },
  {
    id: 8,
    name: "Velocity Sport",
    category: "Running",
    price: 2299,
    quantity: 7,
    description: "Comfortable sports shoes for active use.",
  },
  {
    id: 9,
    name: "Mira Flats",
    category: "Flats",
    price: 1299,
    quantity: 0,
    description: "Simple flats designed for comfortable everyday wear.",
  },
  {
    id: 10,
    name: "Ridge Boots",
    category: "Boots",
    price: 3999,
    quantity: 5,
    description: "Durable boots with a classic everyday design.",
  },
  {
    id: 11,
    name: "Cloud Step",
    category: "Running",
    price: 2699,
    quantity: 9,
    description: "Soft and lightweight shoes for comfortable daily runs.",
  },
  {
    id: 12,
    name: "Harper Mules",
    category: "Slip-ons",
    price: 1799,
    quantity: 4,
    description: "Minimal slip-on mules designed for everyday wear.",
  },
];

export default products;